apiVersion: v1
kind: ResourceQuota
metadata:
 name: compute-quota
 namespace: dev

spec:
 hard:
  pods: "10"
  requests.cpu: "4"
  limits.cpu: "10"
  limits.memory: 10Gi

# The key difference between replica set and replication controller is that replication controller 
# only supports equality-based selector whereas replica set supports set-based selector.
