apiVersion: v1
kind: Pod
metadata:
 name: myapp-pod
 labels:
  app: myapp
spec:
 containers:
  - name: mysql 
    image: mysql
    command: [ "sleep" ]  # Just sleep forever (to prevent CrashLoopBackOff)
    args: [ "infinity" ]

 subdomain: mysql-h
 hostname: mysql-pod
 