apiVersion: v1
kind: Pod
metadata:
 name: simple-webapp
 labels:
  name: simple-webapp
spec:
 containers: # The - sign represents an array in YAML (because we can have multiple containers)
  - name: simple-webapp
    image: simple-webapp
    ports:
      - containerPort: 8080
                     
  - name: log-agent
    image: log-agent


# A simple logging agent for our web application. This is a sidecar design pattern.



 
