apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-vol1
spec:
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 1Gi
 hostPath:
  path: /tmp/data
  
 
# You can replace hostPath with a configuration for a specific Storage 
# Solution like awsElasticBlockStorage in the following snippet-

# awsElasticBlockStore:
#  volumeID: <volume-id>
#  fsType: ext4