apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: myclaim
spec:
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 500Mi

# Persistent volumes are long-term storage in your Kubernetes cluster. 
# Persistent volumes exist beyond containers, pods, and nodes. 
# A Pod uses a Persistent Volume claim to to get read and write access 
# to the Persistent Volume.
