apiVersion: v1
kind: Pod
metadata:
 name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["/bin/sh","-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
    volumeMounts:
    - mountPaths: /opt
      name: data-volume

  volumes:
  - name: data-volume
    hostPath: 
      path: /data
      type: Directory

# You can replace hostPath with a configuration for a specific Storage 
# Solution like awsElasticBlockStorage in the following snippet-

# awsElasticBlockStore:
#  volumeID: <volume-id>
#  fsType: ext4