apiVersion: v1
kind: Service
metadata:
 name: back-end
spec:
 type: ClusterIP
 ports:
  - targetPort: 80
    port: 80
    
 selector:
  app: myapp
  type: back-end

# The targetPort specifies the port to which the Service is to be attached.
# And the labels in selector are then used to identify the Pod with that targetPort. 