apiVersion: v1
kind: Service

metadata:
 name: myapp-service

spec:
 type: NodePort
 ports:
  - targetPort: 80 
    port: 80
    NodePort: 3008

 selector:
  app: myapp
  type: front-end


# The targetPort specifies the port to which the Service is to be attached.
# And the labels in selector are then used to identify the Pod with that targetPort. 