apiVersion: v1
kind: Service
metadata:
 name: nginx-ingress
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
 selector:
  name: nginx-ingress

# The targetPort specifies the port to which the Service is to be attached.
# And the labels in selector are then used to identify the Pod with that targetPort. 