apiVersion: v1
kind: Service
metadata:
 name: my-service

spec:
 selector:
  app: App1
 ports:
  - protocol: TCP
    port: 80
    targetPort: 9376

# This is just a sample Service definition file used in the animations 
# demonstrating the use of Selectors and Annotators.