apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: myapp-deployment
 labels:
  app: myapp

spec:
 serviceName: mysql-h 
 replicas: 3
 selector:
  matchLabels:
   app: mysql
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
    - name: mysql
      image: mysql
      volumeMounts:
       - mountPath: /var/lib/mysql
         name: data-volume
# Copy and Paste from PVC Definition file
volumeClaimTemplates:
 - metadata:
  name: myclaim
 spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: google-storage
  resources:
   requests:
    storage: 500Mi
